---
- name: Echo Hello World
  shell: echo "Hello World"

- name: Install LAMP
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - apache2  
    - mysql-server
    - php5
    - php5-mysql
  become: true

- name: Delete /var/www/html/index.html
  file:
    path: /var/www/html/index.html
    state: absent
  become: true

- name: Check if wordpress is installed
  stat: 
    path: /var/www/html/wordpress
  register: check_wordpress

- debug: var=check_wordpress

- name: Download wordpress and extract file
  unarchive: 
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html
    copy: false # requrie
  when: 
      not check_wordpress.stat.exists
  become: true


- name: Change root document on Apache
  lineinfile:
      dest: /etc/apache2/sites-available/000-default.conf
      regexp: ^\W*DocumentRoot
      line: '        DocumentRoot /var/www/html/wordpress'
  become: true
  notify: Restarst Apache # call handlers
