---
- name: Echo Hello World
  shell: echo "Hello World"

- name: Install LAMP
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - "{{ wordpress_packages }}"
  become: true

- name: Delete "{{ wordpress_document_root }}" index.html
  file:
    path: "{{ wordpress_document_root_index }}"
    state: absent
  become: true

- name: Check if wordpress is installed
  stat:
    path: "{{ wordpress_root_path }}"
  register: check_wordpress

- debug: var=check_wordpress

- name: Download wordpress and extract file
  unarchive:
    src: "{{ wordpress_url_lastest_gz }}"
    dest: "{{ wordpress_document_root }}"
    copy: false # requrie
  when:
      not check_wordpress.stat.exists
  become: true


- name: Change root document on Apache
  lineinfile:
      dest: "{{ wordpress_apache_default_conf }}"
      regexp: ^\W*DocumentRoot
      line: "        DocumentRoot {{ wordpress_root_path}}"
  become: true
  notify: Restarst Apache # call handlers
