- name: Change root document on Apache
  lineinfile:
      dest: "{{ wordpress_apache_default_conf }}"
      regexp: ^\W*DocumentRoot
      line: "        DocumentRoot {{ wordpress_root_path}}"
  notify: Restarst Apache # call handlers

- name: Create wordpress database
  mysql_db:
    name: "{{ wordpress_database_name }}"
    state: present
    login_user: "{{ wordpress_mysql_root_user }}"
    login_password: "{{ wordpress_mysql_root_pass }}"

- name: Copy wp-config.php template
  template:
      src: wp-config.php.j2
      dest: "{{ wordpress_root_path }}/wp-config.php"
